# Generated by Django 3.0.4 on 2020-03-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('fonction', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employe/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
